### ISSUE TITLE
use dynamic path

### ISSUE THREAD

**Issue by bernard-ng** [wilfried-musanzi/election-ng#1]
https://github.com/wilfried-musanzi/election-ng/blob/7917072d7e652046afe8d996fcdeb5aa5581b400/test/fill.php#L5

**Comment by wilfried-musanzi** [comment]
:D thanks Ng

**Comment by wilfried-musanzi** [comment]
@bernard-ng

**Comment by bernard-ng** [comment]
on ferme un issue après l'avoir corriger avec un commit

**Comment by wilfried-musanzi** [comment]
J'ai corrigé je crois, verify.

Le dim. 6 juin 2021 à 02:07, Bernard Ngandu ***@***.***> a
écrit :
